upstream cvat_backend {
    server cvat_server:8080;
}

upstream cvat_ui {
    server cvat_ui:8000;
}

server {
    listen 80;
    server_name localhost;
    client_max_body_size 100M;

    # バックエンド（API・管理画面・静的ファイルなど）へのルーティング
    location ~ ^/(api|git|opencv|analytics|static|admin|documentation|django-rq)/ {
        proxy_pass http://cvat_backend;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # フロントエンド（UI画面）へのルーティング
    location / {
        proxy_pass http://cvat_ui;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}